### ISSUE TITLE
Feature 1: User can  view the list of the Studio Ghibli films

### ISSUE THREAD

**Issue by dulceherrera** [dulceherrera/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can  view the list of the Studio Ghibli films

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user enters the application, they will see the list with images of the Studio Ghibli films.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="737" alt="Screen Shot 2022-08-01 at 10 15 08 AM" src="https://user-images.githubusercontent.com/97363006/182208891-dd073f43-5ea7-4f5d-8d04-73c3fb3df37e.png">

<img width="226" alt="Screen Shot 2022-08-01 at 10 15 31 AM" src="https://user-images.githubusercontent.com/97363006/182208914-3e80b1d7-e027-413c-91ee-31e4c496854d.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make sure the desktop has three columns in each row.
- [x] Make sure the mobile version has one column.
- [x] Make a navigation bar with two tabs. One for the the list and one for the reviews.
- [x] Add `cursor: pointer` for each film when the mouse hovers over them.
- [x] Uses XMLHttpRequest to send a request to the Studio Ghibli API.
- [x] Loop through the response and create an element to hold the image of the each film.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
