### ISSUE TITLE
Feature 2: User can view details of each Studio Ghibli film 

### ISSUE THREAD

**Issue by dulceherrera** [dulceherrera/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the details of each film listed on the app.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks the film, a detail info page will be shown.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="728" alt="Screen Shot 2022-08-01 at 11 04 40 AM" src="https://user-images.githubusercontent.com/97363006/182213138-34edbd60-1bd4-4927-84ab-cd0abcb22bb6.png">

<img width="295" alt="Screen Shot 2022-08-02 at 7 25 43 PM" src="https://user-images.githubusercontent.com/97363006/182511991-9bc23fce-bbd6-4cf2-9305-e8ff4680a43b.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] For details page, create a layout in HTML.
- [x] Make a DOM tree for include all of the information of the list.
- [x] Add a "BACK" button so that the user can return to the list of films.
- [x] Listen for "click" for the image of each film so that, when the user clicks the film, a page with the details will be shown. 
- [x] Make sure it looks good both on desktop and mobile version.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Fix all errors
