### ISSUE TITLE
Feature 3: User can make a review on each Studio Ghibli movie

### ISSUE THREAD

**Issue by dulceherrera** [dulceherrera/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user can write a review of the film they want.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a review page so that the user can write their reviews.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="443" alt="Screen Shot 2022-08-01 at 11 11 59 AM" src="https://user-images.githubusercontent.com/97363006/182217460-cc15c27c-9c25-4917-bf6f-42ba5a6ff3ff.png">
<img width="444" alt="Screen Shot 2022-08-01 at 11 12 15 AM" src="https://user-images.githubusercontent.com/97363006/182217500-73e6ebc7-0d68-460e-906c-376124af2ce8.png">
<img width="444" alt="Screen Shot 2022-08-01 at 11 12 32 AM" src="https://user-images.githubusercontent.com/97363006/182217542-e81014b3-c9e2-49e0-b2ee-1ecabc2d92d7.png">
<img width="444" alt="Screen Shot 2022-08-01 at 11 13 00 AM" src="https://user-images.githubusercontent.com/97363006/182217614-121da6af-e402-4386-87f8-44a06d57e201.png">
<img width="528" alt="Screen Shot 2022-08-03 at 3 42 14 PM" src="https://user-images.githubusercontent.com/97363006/182724898-4702da11-9a8a-4be9-88c5-14222a107f50.png">
<img width="609" alt="Screen Shot 2022-08-01 at 11 15 22 AM" src="https://user-images.githubusercontent.com/97363006/182217728-b06980d7-8c3f-45d9-b4c7-eb62e54df417.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a "ADD REVIEW BUTTON" to the details page of each film.
- [x] Create a form for the review.
- [x] Listen for "click" on "ADD REVIEWS" button. When the user clicks the button, the application should send them to the reviews page.
- [x] The review will be sent to the reviews list. User should be able to see their reviews on the reviews tab.
- [ ] When there are no reviews, the message "NO REVIEWS YET" should be displayed.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Fix errors.
  - [ ] Test all functionality again in a private browsing session.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
