### ISSUE TITLE
Feature 4: User can  edit their reviews

### ISSUE THREAD

**Issue by dulceherrera** [dulceherrera/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will have the opportunity to edit their reviews. 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Add a button to each film to edit the reviews. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="446" alt="Screen Shot 2022-08-01 at 11 24 59 AM" src="https://user-images.githubusercontent.com/97363006/182219032-a4314925-8e2e-44ac-a14e-e2e0f34740eb.png">
<img width="440" alt="Screen Shot 2022-08-01 at 11 25 17 AM" src="https://user-images.githubusercontent.com/97363006/182219042-1494e2a4-4f60-4135-96f4-43d43d81590f.png">
<img width="442" alt="Screen Shot 2022-08-01 at 11 25 52 AM" src="https://user-images.githubusercontent.com/97363006/182219048-a47a7d57-d371-4af2-ab35-375dadb70bc3.png">
<img width="684" alt="Screen Shot 2022-08-01 at 11 23 50 AM" src="https://user-images.githubusercontent.com/97363006/182219056-ff7ee133-15a5-4be2-a161-029e20370130.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a "EDIT REVIEW" button to `data-view="review-list"` and place it on the right side of each review. 
- [x] Make an event delegation in the reviews page. The user should be able to click the edit button. 
- [x] To save the review after being edited, modify the function 'submitReview"
- [x] Make sure the reviews tab shows the new review. 
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Fix all errors.
  - [x] Test all functionality again in a private browsing session.
