### ISSUE TITLE
Feature 5: User can delete their reviews

### ISSUE THREAD

**Issue by dulceherrera** [dulceherrera/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

If the users change their mind, they can remove their review from the film. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Add a delete button and create a modal to confirm if they are sure to delete their review.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="442" alt="Screen Shot 2022-08-01 at 11 30 54 AM" src="https://user-images.githubusercontent.com/97363006/182219817-7cf01827-eabb-4a5e-a6a4-25d1740d99c4.png">
<img width="442" alt="Screen Shot 2022-08-01 at 11 31 13 AM" src="https://user-images.githubusercontent.com/97363006/182219832-d4574c3d-3adc-4a85-b424-1a08a7cfac35.png">
<img width="440" alt="Screen Shot 2022-08-01 at 11 31 31 AM" src="https://user-images.githubusercontent.com/97363006/182219839-3cfba221-9499-499c-9060-d019de77b88c.png">
<img width="688" alt="Screen Shot 2022-08-01 at 11 32 07 AM" src="https://user-images.githubusercontent.com/97363006/182219844-a6f14bfd-e32d-4e73-afe9-bf428e1f3e1a.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a "DELETE" button to the `data-view="review-page` so that it appears when the user is editing their review.
- [x] Listen for "click" for the delete button to show a confirmation modal.
- [x] Hide modal when the user clicks the "CANCEL" button.
- [x] Remove the review from the data model.
- [x] Remove the review from the DOM tree.
- [x] Remove all console logs.
- [x] Remove all CSS properties that have no effect.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x]  Test all functionality again in a private browsing session.
- [x] Fix all errors.
